spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/boarddb
    username: boarduser
    password: boardpass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
